### ISSUE TITLE
Support for PSQL attached partition by hash ? 

### ISSUE THREAD

**Issue by mikesimard** [cloudspannerecosystem/harbourbridge#158]
## Found Behavior
I've been running harbourbridge on some of my PSQL schema to test how hard a migration to Google Spanner would be. 

One of the main key of our project is that some of our table has the PostgreSQL 12 partition strategy. 

Running a first pass on a config schema went perfectly. Doing a test on a more complex schema end-up doing a failed to parse the data file. 

I'm doing a simple pgdump in schema only mode: 
`
pg_dump -h myhost -d mydb -U myusername -s -n myschemaname| $GOPATH/bin/harbourbridge -driver=pg_dump -dbname=my-destination-db
`
which result in: 

```
Using driver (source DB): pg_dump target-db: spanner
Generating schema: 100%
Failed to parse the data file: Error parsing last 6404 line(s) of inputpanic: failed to parse the data file

goroutine 1 [running]:
main.main()
        /app/go/pkg/mod/github.com/cloudspannerecosystem/harbourbridge@v0.0.0-20210811071152-f98dc5b0fd75/main.go:157 +0xecc
root@2462e825148a:/app#
```

So I export my pg_dump to a file to see what line 6404 was all about. Which is the exact spot where the first partitioned table get created in the script order. 

`
sed -n '6403,6405'p pgdump.txt
ALTER INDEX affiliate.affiliate_referral_code_pk ATTACH PARTITION affiliate.referral_code_0_pkey;
`

## Expected Behavior
If a statement isn't supported I would expect to get it back on the report and have harbourbridge go ahead with the dump migration completion. 

## Steps to Reproduce the Problem

1. Get a simple table that has a partition by hash strategy on a PG12 instance. 
2. Pass a pg_dump of that table to harbourbridge. 

## Specifications

- Version: 
- Platform:

**Comment by mikesimard** [comment]
Does anyone as experience such behavior when migrating a table that has partition support ?

**Comment by Deep1998** [comment]
Hey @mikesimard, thanks for reaching out. We ran some sample dump files and discovered harbourbridge can successfully parse and convert the `CREATE TABLE` statements with partition support. The issue you are getting seems to be particularly for 
`ALTER INDEX affiliate.affiliate_referral_code_pk ATTACH PARTITION affiliate.referral_code_0_pkey;`
when we try to attach partitions to an index because the current parser is unable to process this statement.
The fix right now is to manually remove these `ALTER INDEX index_name ATTACH PARTITION partition_name;` from the dump and try to re-run harbourbridge. Please circle back if it still causes an error.

On a side note, automatically skipping lines that failed to parse is a known limitation in harbourbridge that we are still working on.

**Comment by manitgupta** [comment]
@mikesimard Is this still an issue?
